import "../assets/img/headerLeftImage.png";
import "../assets/img/Star.svg";
import "../assets/img/HalfMiniLogo.svg";
import "../assets/img/level-one.svg";
import "../assets/img/verified.svg";
import "../assets/img/makeUpSample.png";
import "../assets/img/level-two.svg";
import "../assets/img/level-three.svg";
import "../assets/img/level-four.svg";
import "../assets/img/ProfilrCeo.png";
import "../assets/img/BigCeoPhoto.png";
import "../assets/img/level-five.svg";
import "../assets/img/miniLogo.svg";
import "../assets/img/headerRightImage.png";
import "../assets/img/middleImage.png";
import "../assets/img/mobileSearch.svg";
import "../assets/img/user1.png";
import "../assets/img/user2.png";
import "../assets/img/user3.png";
import "../assets/img/user4.png";
import "../assets/img/lastUser.png";
import "../assets/img/clint-frist.png";
import "../assets/img/clint-second.png";
import "../assets/img/thrid-clint.png";
import "../assets/img/onek.png";
import "../assets/img/CrownIcon.svg";
import "../assets/img/DataIcon.svg";
import "../assets/img/educateHat.svg";
import "../assets/img/HeartIcon.svg";
import "../assets/img/ShopIcon.svg";
import "../assets/img/bannerImage.jpg";
import "../assets/img/Brows.svg";
import "../assets/img/Lumina.svg";
import "../assets/img/lashes.svg";
import "../assets/img/Skin.svg";
import "../assets/img/mainLogo.svg";
import "../assets/img/userIcon.svg";
import "../assets/img/shoppingCartIcon.svg";
import "../assets/img/magnifying-glass-solid.svg";
import "../assets/img/mobileMenu.svg";
import "../assets/img/sets.png";
import "../assets/img/outlet.png";
import "../assets/img/Einrichtung.png";
import "../assets/img/Schulungen.png";
import "../assets/img/pflege-and-zubehor.png";
import "../assets/img/farben.png";
import "../assets/img/waximg.png";
import "../assets/img/lifting.png";
import "../assets/img/kleber.png";
import "../assets/img/pinzetten.png";
import "../assets/img/lashes.png";
import "../assets/img/studioausstattung.png";
const PathImage = {
  headerLeftImage: "/src/assets/img/headerLeftImage.png",
  headerRightImage: "/src/assets/img/headerRightImage.png",
  middleImage: "/src/assets/img/middleImage.png",
  user1: "/src/assets/img/user1.png",
  user2: "/src/assets/img/user2.png",
  user3: "/src/assets/img/user3.png",
  user4: "/src/assets/img/user4.png",
  lastUser: "/src/assets/img/lastUser.png",
  CrownIcon: "/src/assets/img/CrownIcon.svg",
  DataIcon: "/src/assets/img/DataIcon.svg",
  educateHat: "/src/assets/img/educateHat.svg",
  HeartIcon: "/src/assets/img/HeartIcon.svg",
  ShopIcon: "/src/assets/img/ShopIcon.svg",
  Skin: "/src/assets/img/Skin.svg",
  brows: "/src/assets/img/Brows.svg",
  lumina: "/src/assets/img/Lumina.svg",
  lashes: "/src/assets/img/lashes.svg",
  mainLogo: "/src/assets/img/mainLogo.svg",
  shoppingCart: "/src/assets/img/shoppingCartIcon.svg",
  userIcon: "/src/assets/img/userIcon.svg",
  searchIcon: "/src/assets/img/magnifying-glass-solid.svg",
  mobileMenu: "/src/assets/img/mobileMenu.svg",
  mobileSearch: "/src/assets/img/mobileSearch.svg",
  onek: "/src/assets/img/onek.png",
  miniLogo: "/src/assets/img/miniLogo.svg",
  levelOne: "/src/assets/img/level-one.svg",
  levelTwo: "/src/assets/img/level-two.svg",
  levelThree: "/src/assets/img/level-three.svg",
  levelFour: "/src/assets/img/level-four.svg",
  levelFive: "/src/assets/img/level-five.svg",
  bannerImage: "/src/assets/img/bannerImage.jpg",
  sets: "/src/assets/img/sets.png",
  outlet: "/src/assets/img/outlet.png",
  Einrichtung: "/src/assets/img/Einrichtung.png",
  Schulungen: "/src/assets/img/Schulungen.png",
  pflege: "/src/assets/img/pflege-and-zubehor.png",
  farben: "/src/assets/img/farben.png",
  waxing: "/src/assets/img/waximg.png",
  lifting: "/src/assets/img/lifting.png",
  kleber: "/src/assets/img/kleber.png",
  pinzetten: "/src/assets/img/pinzetten.png",
  lashe: "/src/assets/img/lashes.png",
  studio: "/src/assets/img/studioausstattung.png",
  clintFrist: "/src/assets/img/clint-frist.png",
  clintSecond: "/src/assets/img/clint-second.png",
  ClintThrid: "/src/assets/img/thrid-clint.png",
  star: "/src/assets/img/Star.svg",
  vrified: "/src/assets/img/verified.svg",
  miniCeo: "/src/assets/img/ProfilrCeo.png",
  mainCeo: "/src/assets/img/BigCeoPhoto.png",
  makeUpSample: "/src/assets/img/makeUpSample.png",
  halfMiniLogo: "/src/assets/img/HalfMiniLogo.svg",
};
export default PathImage;
